; Giới hạn upload — post_max_size = tổng body POST; upload_max_filesize = từng file
date.timezone = Asia/Ho_Chi_Minh
upload_max_filesize = 25M
post_max_size = 50M
max_file_uploads = 30
memory_limit = 512M
max_execution_time = 300
max_input_time = 300
